ONSdigital/dp-dimension-extractor

- .gitignore
- README.md
Describe what you have changed and why.
Describe the steps required to test the changes.
Describe who worked on the changes, so that other people can review.
> update readme and add gitignore

- handler/handler.go
- service/service.go
- vendor/github.com/ONSdigital/go-ns/kafka/consumer-group.go
- vendor/github.com/ONSdigital/go-ns/kafka/global.go
- vendor/github.com/ONSdigital/go-ns/kafka/producer.go
- vendor/vendor.json
match the new kafka interfaces
> update kafka lib usage to use feature/kafka-add

- README.md
- config/config.go
- config/config_test.go
- dimension/extraction.go
- dimension/extraction_test.go
- dimension/request.go
- instance/request.go
- instance/request_test.go
- main.go
- service/handler.go
- service/service.go
Allow import API auth token to be injected via environment variable.
Check code changes.
*
> Allow import API auth token to be injected via environment variable.

- dp-dimension-extractor.nomad
> Add nomad script.

- dp-dimension-extractor.nomad
fix artifacts for build + deployment.
@LloydGriffiths
> fix artifacts for build + deployment.

- README.md
- config/config.go
Update dataset API auth token environment variable name.
> Update dataset API auth token environment variable name.

- codelists/request.go
- vendor/github.com/gopherjs/gopherjs/LICENSE
- vendor/github.com/gopherjs/gopherjs/js/js.go
- vendor/vendor.json
Fixed vendoring to allow app to build in CI
Check the changes are sensible and that the branch is passing in CI
Anyone
> Fix incorrect import and add missing dependency

- dimension/extraction.go
- dimension/extraction_test.go
- dimension/request.go
Push labels from dimensions to the dataset-api
Review code and run tests
anyone
> Push labels to the dataset-api

- codelists/request.go
- codelists/request_test.go
- codelists/testcodelist/importclient.go
- service/handler.go
Added auth token to get instance
review the code
anyone
> Added auth token when getting an instance from the dataset api

- README.md
Merge cmd-develop into cmd-master
Ensure that the merge is from cmd-develop into cmd-master
Anyone
> Merge cmd-develop into cmd-master

- vendor/github.com/ONSdigital/dp-reporter-client/LICENSE.md
- vendor/github.com/ONSdigital/dp-reporter-client/model/model.go
- vendor/github.com/ONSdigital/dp-reporter-client/reporter/report_event_client.go
- vendor/github.com/ONSdigital/dp-reporter-client/reporter/reportertest/kafka_producer_mock.go
- vendor/github.com/ONSdigital/dp-reporter-client/reporter/reportertest/report_event_client.go
- vendor/github.com/ONSdigital/dp-reporter-client/schema/schemas.go
- vendor/github.com/ONSdigital/go-ns/kafka/consumer-group.go
- vendor/github.com/pkg/errors/LICENSE
- vendor/github.com/pkg/errors/README.md
- vendor/github.com/pkg/errors/appveyor.yml
- vendor/github.com/pkg/errors/errors.go
- vendor/github.com/pkg/errors/stack.go
- vendor/vendor.json
Use updated kafka lib with indefinite offset retention
> Use updated kafka lib with indefinite offset retention

- README.md
- ci/build.yml
- ci/unit.yml
- codelists/request.go
- codelists/request_test.go
- config/config.go
- config/config_test.go
- dimension/extraction.go
- dimension/extraction_test.go
- dimension/request.go
- dimension/request_test.go
- event/consumer.go
- event/consumer_test.go
- instance/request.go
- instance/request_test.go
- main.go
- service/service.go
See title
Check changes make sense. Until all services have been updated with new authentication, it will be hard to test successfully.
Team B
> Add new service auth token as a header to outbound http requests

- config/config.go
Process environment variables before adding bearer
> Process environment variables before adding bearer

- config/config.go
- config/config_test.go
> Enable encryption by default

- README.md
Fix merge conflict in readme
See changes
Anyone
> Fix merge conflict in readme

- README.md
Update readme
Verify it makes sense
Anyone
> Update README to include AWS credentials configuration

- service/service.go
- vendor/github.com/ONSdigital/s3crypto/s3crypto.go
- vendor/github.com/aws/aws-sdk-go/aws/config.go
- vendor/github.com/aws/aws-sdk-go/aws/types.go
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/github.com/aws/aws-sdk-go/internal/sdkio/io_go1.6.go
- vendor/github.com/aws/aws-sdk-go/internal/sdkio/io_go1.7.go
- vendor/github.com/aws/aws-sdk-go/internal/sdkrand/locked_source.go
- vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/batch.go
- vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/bucket_region.go
- vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/doc.go
- vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go
- vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go
- vendor/vendor.json
Update s3crypto lib to fix encryption
Verify logic correct
Anyone
> Update s3crypto library to fix encryption

- vendor/github.com/ONSdigital/s3crypto/s3crypto.go
- vendor/vendor.json
Update s3crypto
Verify its updated
Anyone
> Update to avoid reading whole file into memory

- dp-dimension-extractor.nomad
What
Using docker reduces the likelihood of timeout on deploy
How to review
check for typos
check repo names are consistent
check web/publishing both updated
Who can review
anyone
> Update nomad plan to use docker instead of exec driver

- README.md
Update license date in readme (to force rebuild and pickup secrets change)
sanity check
anyone
> Update license date in readme (to force rebuild)

- main.go
Service identity validated channel only true if validation was successful 
serviceIdentityValidated channel only receives true if checkServiceIdentity is successful
anyone
> Service identity validated channel only true if validation success

- go.mod
- go.sum
- Update Kafka dependency 
- once deployed, the memory leak should not happen again
Anyone
> Updated kafka to v1.1.5 with memory leak fix

- Makefile
- ci/audit.yml
- ci/scripts/audit.sh
Added dependency auditing to dimension extractor
Check scripts and make sure `make audit` runs
Anyone
> Added dependency auditing

- go.mod
- service/service.go
Add error formatting and stack trace to captured panic logs
Sanity check
Rhys 😄
> Add error formatting and stack trace to captured panic logs

- go.mod
- go.sum
See title.
Ensure audit and unit tests pass as expected.
Anyone but me.
> Update application dependencies.

- service/service.go
handle error in header row - first column not having underscore
check develop no longer falls over
You
> handle error in header row - first column not having underscore

- README.md
This done to get new deployment with new gpg key.
Check only one char changed in README.md
Anyone
> Add extra appearance char to force deployment with new gpg key
